apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: webapps
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: vikramsinhshinde/devops:test-1  # Your custom image
        ports:
        - containerPort: 8084  # Updated to 8084
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: webapps
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8084  # Service will expose port 8084
      targetPort: 8084  # Target port inside the container
  type: ClusterIP  # Change to LoadBalancer for external access if needed
